spring:
  application:
    name: service-registry

server:
  port: ${port:8761}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false